version: '3.1'
services:
  db:
    image: postgres
    restart: always
    container_name: pdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: test
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5433:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

